# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "node1", primary: true do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.hostname = 'node1'
    node.vm.network :private_network, ip: "192.168.56.101"
    node.vm.network "forwarded_port", guest: 80, host: 1234
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "node1"
    end
  end

  config.vm.define "node2" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.hostname = 'node2'
    node.vm.network :private_network, ip: "192.168.56.102"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "node2"
    end
  end

  config.vm.define "node3" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.hostname = 'node3'
    node.vm.network :private_network, ip: "192.168.56.103"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "node3"
    end
  end

  config.vm.boot_timeout = 120
  config.vm.synced_folder "../data", "/data"

end

