Vagrant.configure("2") do |config|
    # 定义虚拟机数量
    vms = Array(1..3)
    vms.each do |i|
        config.vm.define "peer#{i}" do |peer|
            # 设置虚拟机的Box
            peer.vm.box = "centos/7"
            # 不检查 box 更新
            peer.vm.box_check_update = false 
            # 设置虚拟机的主机名
            peer.vm.hostname="peer#{i}.node"
            # 设置虚拟机的IP (wlp2s0 为桥接本机的网卡)
            peer.vm.network "public_network", ip: "192.168.1.1#{i}",bridge: "en0"
            # VirtaulBox相关配置
            peer.vm.provider "virtualbox" do |v|
                # 设置虚拟机的名称
                v.name = "peer#{i}"
                # 设置虚拟机的内存大小  
                v.memory = 2048 
                # 设置虚拟机的CPU个数
                v.cpus = 1
            end
            # 增加各节点 host 配置
            config.vm.provision :hosts do |provisioner|
                vms.each do |x|
                    provisioner.add_host "192.168.1.1#{x}", ["peer#{x}.node"]
                end
            end
            # 每次开机后重启 network 和 ssh，解决公网网卡不启动问题 
            peer.vm.provision "shell", run: "always", inline: <<-SHELL
                sed -i "s?PermitRootLogin\ without-password?PermitRootLogin\ yes?g" /etc/ssh/sshd_config
                systemctl restart sshd
            SHELL
        end
    end
end
